version: '3.8'
 
services:
 yolov3:
   build:
     context: ./YoloV3
   image: josevaldojnr/yolov3_ws:latest    
   container_name: yolov3  
   volumes:
     - ./YoloFiles:/app
     - /tmp/.X11-unix:/tmp/X11-unix
     - /dev/video0:/dev/video0  
   environment:
     - DISPLAY=${IP_DISPLAY}
   network_mode: host
   devices:
     - /dev/video0:/dev/video0
     - /dev/video1:/dev/video1
   privileged: true  
 
 yolov5:
   build:
     context: ./YoloV5
   container_name: yolov5
   image: josevaldojnr/yolov5_ws:latest    
   volumes:
     - ./YoloFiles:/app
     - /tmp/.X11-unix:/tmp/X11-unix
     - /dev/video0:/dev/video0  
   environment:
     - DISPLAY=${IP_DISPLAY}
   network_mode: host
   devices:
     - /dev/video0:/dev/video0
     - /dev/video1:/dev/video1
   privileged: true 

 yolov10:
   build:
     context: ./YoloV10
   container_name: yolov10     
   image: josevaldojnr/yolov10_ws:latest    
   volumes:
     - ./YoloFiles:/app
     - /tmp/.X11-unix:/tmp/X11-unix
     - /dev/video0:/dev/video0  
   environment:
     - DISPLAY=${IP_DISPLAY}
   network_mode: host
   devices:
     - /dev/video0:/dev/video0
     - /dev/video1:/dev/video1
   privileged: true

 yolov11:
   build:
     context: ./YoloV11
   container_name: yolov11
   image: josevaldojnr/yolov11_ws:latest  
   volumes:
     - ./YoloFiles:/app
     - /tmp/.X11-unix:/tmp/X11-unix
     - /dev/video0:/dev/video0  
   environment:
     - DISPLAY=${IP_DISPLAY}
   network_mode: host
   devices:
     - /dev/video0:/dev/video0
     - /dev/video1:/dev/video1
   privileged: true     
