FROM python:3.7-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-opencv \
    x11-apps \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libopencv-dev

RUN pip install notebook

RUN pip install torch==1.4.0 torchvision==0.5.0

RUN pip install opencv-python

COPY . .

EXPOSE 8093
EXPOSE 8083



CMD ["bash", "-c","jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --port=8093 --NotebookApp.token='' --NotebookApp.password=''"]




